global:
  ssh_port: 22
  container_image: docker.io/cubefs/cbfs-base:1.0-golang-1.17.13
  data_dir: /data
  bin_dir: /bin
  variable:
    target: 0.0.1

master:
  config:
    listen: 17010
    prof: 17020
    data_dir: /data

metanode:
  config:
    listen: 17210
    prof: 17220
    data_dir: /data

datanode:
  config:
    listen: 17310
    prof: 17320
    data_dir: /data


deplopy_hosts_list:
  master:
    hosts:
      - 192.168.128.128
  metanode:
    hosts:
      - 192.168.128.128
  datanode:
    - hosts: 192.168.128.128
      disk:
        - path: /data/disk0
          size: 10737418240