global:
  ssh_port: 22
  container_image: docker.io/cubefs/cbfs-base:1.0-golang-1.17.13
  data_dir: /data
  variable:
    target: 0.0.1

master:
  config:
    listen: 17010
    prof: 17020
    data_dir: /data

metanode:
  config:
    listen: 17210
    prof: 17220
    data_dir: /data

datanode:
  config:
    listen: 17310
    prof: 17320
    data_dir: /data


deplopy_hosts_list:
  master:
    hosts:
      - 192.168.128.128
      - 192.168.128.129
      - 192.168.128.130
  metanode:
    hosts:
      - 192.168.128.134
      - 192.168.128.135
      - 192.168.128.136
  datanode:
    - hosts: 192.168.128.131
      disk:
        - /data0
    - hosts: 192.168.128.132
      disk:
        - /data0
        - /data1
    - hosts: 192.168.128.133
      disk:
        - /data2
        - /data3